improve error message

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -160,7 +160,7 @@ runs:
           # Validate Rasa version
           CHECK_VERSION=$(curl --silent ${DOCKERHUB_TAGS_URL} | jq -r '.results[] | select(.name=="${{ inputs.rasa_version }}") | .name')
           if [[ "$CHECK_VERSION" != "${{ inputs.rasa_version }}" ]]; then
-            echo "::error::Rasa in ${{ inputs.rasa_version }} version doesn't exist. Check if the given Rasa version is valid, https://hub.docker.com/r/rasa/rasa/tags" && exit 1
+            echo "::error::Rasa version ${{ inputs.rasa_version }} doesn't exist. Check if the given Rasa version is valid, https://hub.docker.com/r/rasa/rasa/tags" && exit 1
           fi
           RASA_VERSION=${{ inputs.rasa_version }}
         fi
