Use 'rasa init' in the CI

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -9,8 +9,48 @@ on:
 
 env:
   RASA_X_DEMO_VERSION: '0.33.0'
+  RASA_IMAGE_TAG: '2.1.3-full'
 
 jobs:
+  test_action_init:
+    runs-on: ubuntu-latest
+    name: Test GH action - rasa init
+
+    steps:
+    - uses: actions/checkout@v2
+
+    - name: Create a new project
+      run: |
+        mkdir rasa-project
+        chmod 777 rasa-project
+        docker run --rm -v ${{ github.workspace }}/rasa-project:/rasa-project rasa/rasa:${{ env.RASA_IMAGE_TAG }} init --no-prompt --init-dir /rasa-project
+
+    - name: Download Rasa X model
+      run: |
+        wget https://github.com/RasaHQ/rasa-x-demo/blob/0.33.0/models/model.tar.gz?raw=true \
+          -O test_model.tar.gz
+
+    - id: action
+      name: Rasa Test & Train - rasa init
+      uses: ./
+      with:
+        rasa_version: ${{ env.RASA_IMAGE_TAG }}
+        workspace: ${{ github.workspace }}/rasa-project
+        test_type: all
+        github_token: ${{ secrets.GITHUB_TOKEN }}
+        configuration_name: 'rasa-init'
+        publish_summary: 'false'
+
+    - name: Checkout output
+      run: |
+        echo ${{ fromJSON(steps.action.outputs.report).default['rasa-init'].intent_classification.accuracy }}
+
+    - name: Checkout output - if
+      if: fromJSON(steps.action.outputs.report).default['rasa-init'].intent_classification.accuracy <= 0.5
+      run: |
+        echo "::error::${{ fromJSON(steps.action.outputs.report).default['rasa-init'].intent_classification.accuracy }}"
+        exit 1
+
   # Test the GH action on Rasa X Demo data
   # https://github.com/RasaHQ/rasa-x-demo
   test_action_x:
